name: All Installers
run-name: ${{ inputs.cura_conan_version }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      cura_conan_version:
        description: 'CuraLE Conan Version'
        default: 'curale/[*]@lulzbot/testing'
        type: string
      conan_args:
        description: 'Conan args, e.g. --requires'
        default: ''
        type: string
      enterprise:
        description: 'Build CuraLE as an Enterprise edition'
        default: false
        type: boolean
      staging:
        description: 'Use staging API'
        default: false
        type: boolean


jobs:
  installers:
    name: Create installers
    uses: lulzbot3d/CuraLE_Workflows/.github/workflows/cura-installers.yml@main
    with:
      cura_conan_version: ${{ inputs.cura_conan_version }}
      conan_args: ${{ inputs.conan_args }}
      enterprise: ${{ inputs.enterprise }}
      staging: ${{ inputs.staging  }}
    secrets: inherit
