name: Weekly Build - Stable Release
run-name: Weekly Build - Stable Release

on:
  workflow_call:
#   schedule:
#     # Runs at 18:00 CST on Fridays
#     - cron: '0 0 * * 6'

jobs:
  build-nightly:
    uses: ./.github/workflows/nightly.yml
    with:
      cura_conan_version: "curale/[*]"
      release_tag: "nightly-stable"
      caller_workflow: "nightly-stable.yml"
    secrets: inherit
